### ISSUE TITLE
Improve usability without requiring command-line

### ISSUE THREAD

**Issue by Breakthrough** [Breakthrough/DVR-Scan#178]
Right now a GUI for DVR-Scan is in development, but not available yet.  In the meantime, Windows users can create a helper script easily with Notepad.  Copy and paste either (1) or (2) below into notepad and save it as a file called `dvr-scan.bat`:

  1. To scan without region editor:

```
ECHO OFF
dvr-scan.exe -i %*
PAUSE
```
  2. To scan with region editor:

```
ECHO OFF
dvr-scan.exe -r -i %*
PAUSE
```

Copy and paste exactly those lines into notepad, and click File -> Save As..., and save it somewhere with the name `dvr-scan.bat`.  You can then drag and drop the video(s) you want to scan ontop of that .bat file.  By default, the output will be saved to the folder where the videos come from.  You can configure this by setting the `output-dir` option in a config file.

To use a config file:

  1. Copy the following path and paste it into Windows Explorer:
  ```
C:/Users/%USERNAME%/AppData/Local
```
  
  2. Open the folder called `DVR-Scan` or create one if it does not exist. The folder name is case sensitive.
  3. Open the file `dvr-scan.cfg` with Notepad. If it does not exist, right-click and save [the config file template](https://raw.githubusercontent.com/Breakthrough/DVR-Scan/releases/1.6/dvr-scan.cfg) inside the `DVR-Scan` folder.
  4. Edit the config file to set the options you want (see instructions at the top). Lines starting with `#` are ignored and treated as comments.  For example to override a config option, remove the `#` at the beginning of an option and set the value.

DVR-Scan will output a log message showing what config file it is using.  The next release of DVR-Scan will create this folder for you when you use the installer, so sorry right now it is a manual process. I'm also actively developing a full GUI interface for DVR-Scan which should alleviate a lot of these issues.  Most of the ground work will be done in the upcoming release with the new region editor, after which adding new features like this will become much easier.

## Tasks

 - [ ] Allow using `-r`/`--region-editor` without an explicit `-i`/`--input` flag, upon which DVR-Scan should prompt the user for what video(s) to scan
 - [ ] Add a desktop shortcut with the installer that launches the region editor in prompt-for-files mode
     - launch the region editor with a static background image or just grey to indicate the program is open 
 - [ ] Make the default region closer to the borders of the frame
     - Ensure that the full frame is scanned by default if the user skips editing the default region, even though it will be spaced a bit from the video border to provide better visual cues of the region's control handles

**Comment by Breakthrough** [comment]
The next release of DVR-Scan will include a much improved region editor that  paves the way for a full GUI.  In the meantime, the workarounds above should suffice for most users, and also allow using the new region editor more seamlessly.  This should be revisited once the new release is out, since we might be able to have a full GUI mode.

**Comment by Breakthrough** [comment]
v1.7 is now out!
