### ISSUE TITLE
v1.6.2 Release Checklist

### ISSUE THREAD

**Issue by Breakthrough** [Breakthrough/DVR-Scan#183]
To help get more releases out sooner with the ongoing changes to the region editor, a new release should be cut soon to get some feedback.  This means some items will be pushed to a follow-up release.  The region editor changes pave the way for a full-fledged UI, so feedback is critical to keep development going.

Open Items for v1.6.2 release:

 - [x] Make sure #170 is documented on changelog
 - [x] Ensure documentation is updated for new region editor (#181)
 - [x] Replace documentation in both package and installed versions with HTML generated copy
 - [x] Include config file in correct path when installing so users can edit it in-place by commenting out values
 - [x] Add link to drag-n-drop shortcuts from #178 as an FAQ entry or in a call-out in the user guide
